export const REMOVE_FROM_COLLECTION = 'REMOVE_FROM_COLLECTION';
export const ADD_TO_COLLECTION = 'ADD_TO_COLLECTION';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const CHANGE_STATUS = 'CHANGE_STATUS';
export const RECIVE_DATA = 'RECIVE_DATA';
export const SHOW_GIF = 'SHOW_GIF';
export const SET_USER = 'SET_USER';
export const SIGN_UP = 'SIGN_UP';
